/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import Strategy.Veiculo;
import javax.swing.JOptionPane;

/**
 *
 * @author William
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        lblPrecoValorEstimado.setText("0.00");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValorMercado = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblTipoVeiculo = new javax.swing.JLabel();
        cboxTipoVeiculo = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        cboxEstado = new javax.swing.JComboBox<>();
        lblValorEstimado = new javax.swing.JLabel();
        btnSimulador = new javax.swing.JButton();
        lblPrecoValorEstimado = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        txtfValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblValorMercado.setText("Valor de mercado do veículo");

        lblValor.setText("R$");

        lblTipoVeiculo.setText("Tipo de veículo");

        cboxTipoVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Particular e Passeio", "Caminhonetes e Utilitários", "Transporte de Passageiros", "Motocicletas e Quadriciculos", "Locadora de Veículos", "Ônibus e Caminhões" }));

        lblEstado.setText("Estado");

        cboxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espírito Santo" }));
        cboxEstado.setEnabled(false);

        lblValorEstimado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblValorEstimado.setText("Valor estimado do IPVA:  R$");

        btnSimulador.setText("SIMULAR");
        btnSimulador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimuladorActionPerformed(evt);
            }
        });

        lblPrecoValorEstimado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimulador)
                                .addGap(72, 72, 72)
                                .addComponent(lblValorEstimado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPrecoValorEstimado)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblValor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfValor))
                                    .addComponent(lblValorMercado))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipoVeiculo)
                                    .addComponent(cboxTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEstado)
                                    .addComponent(cboxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorMercado)
                            .addComponent(lblTipoVeiculo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValor)
                            .addComponent(cboxTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimulador)
                    .addComponent(lblValorEstimado)
                    .addComponent(lblPrecoValorEstimado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpar)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    
    private void btnSimuladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimuladorActionPerformed
        try {   
            double valorVeiculo = Double.valueOf(txtfValor.getText().toString());
            int tipoVeiculo = cboxTipoVeiculo.getSelectedIndex() + 1;
            double valorIPVA = 0;

            switch(tipoVeiculo){
                case 1:
                    valorIPVA = new Veiculo(Veiculo.PARTICULAR_E_PASSEIO, valorVeiculo).resultadoValorIPVA();
                    break;
                case 2:
                    valorIPVA = new Veiculo(Veiculo.CAMINHONETES_E_UTILITARIOS, valorVeiculo).resultadoValorIPVA();
                    break;
                case 3:
                    valorIPVA = new Veiculo(Veiculo.TRANSPORTE_DE_PASSAGEIROS, valorVeiculo).resultadoValorIPVA();
                    break;
                case 4:
                    valorIPVA = new Veiculo(Veiculo.MOTOCICLETAS_E_QUADRICICULOS, valorVeiculo).resultadoValorIPVA();
                    break;
                case 5:
                    valorIPVA = new Veiculo(Veiculo.LOCADORA_DE_VEICULOS, valorVeiculo).resultadoValorIPVA();
                    break;
                case 6:
                    valorIPVA = new Veiculo(Veiculo.ONIBUS_E_CAMINHOES, valorVeiculo).resultadoValorIPVA();
                    break;
                default:
                    throw new RuntimeException("TIPO DE VEÍCULO NÃO ENCONTRADO.");
        }
        
            lblPrecoValorEstimado.setText(String.valueOf(valorIPVA));
        } catch (Exception mensagemERRO){
            JOptionPane.showMessageDialog(this, mensagemERRO, "Verifique os campos e tente novamente", JOptionPane.ERROR_MESSAGE);
        }
        
       
        
        
    }//GEN-LAST:event_btnSimuladorActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtfValor.setText("");
        lblPrecoValorEstimado.setText("0.00");
        cboxTipoVeiculo.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSimulador;
    private javax.swing.JComboBox<String> cboxEstado;
    private javax.swing.JComboBox<String> cboxTipoVeiculo;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblPrecoValorEstimado;
    private javax.swing.JLabel lblTipoVeiculo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValorEstimado;
    private javax.swing.JLabel lblValorMercado;
    private javax.swing.JTextField txtfValor;
    // End of variables declaration//GEN-END:variables
}
