/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.sistemarevenda;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author William
 */
public class Cadastro extends javax.swing.JDialog {

    /**
     * Creates new form Cadastro
     */
    public Cadastro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        mnuPopupLista = new javax.swing.JPopupMenu();
        mnuEditar = new javax.swing.JMenuItem();
        mnuManutencao = new javax.swing.JMenuItem();
        Panel_Cadastro = new javax.swing.JPanel();
        Label_Marca = new javax.swing.JLabel();
        Label_Modelo = new javax.swing.JLabel();
        Label_Ano = new javax.swing.JLabel();
        Label_Cor = new javax.swing.JLabel();
        TextField_Modelo = new javax.swing.JTextField();
        TextField_Marca = new javax.swing.JTextField();
        TextField_Cor = new javax.swing.JTextField();
        Spinner_Ano = new javax.swing.JSpinner();
        Label_PMotor = new javax.swing.JLabel();
        Spinner_PMotor = new javax.swing.JSpinner();
        Label_Combustivel = new javax.swing.JLabel();
        ComboBox_Combustivel = new javax.swing.JComboBox<>();
        Label_Cambio = new javax.swing.JLabel();
        Label_Direcao = new javax.swing.JLabel();
        ComboBox_Cambio = new javax.swing.JComboBox<>();
        ComboBox_Direcao = new javax.swing.JComboBox<>();
        Label_CADASTRO = new javax.swing.JLabel();
        Panel_DadosCompra = new javax.swing.JPanel();
        Label_Fornecedor = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Label_Data = new javax.swing.JLabel();
        TextField_Valor = new javax.swing.JTextField();
        TextField_Fornecedor = new javax.swing.JTextField();
        FTextField_Data = new javax.swing.JFormattedTextField();
        Label_PlacaCarro = new javax.swing.JLabel();
        TextField_Placa = new javax.swing.JTextField();
        Button_Adicionar = new javax.swing.JButton();
        Button_Editar = new javax.swing.JButton();
        Button_Excluir = new javax.swing.JButton();
        Panel_Lista = new javax.swing.JPanel();
        ScrollPane_Lista = new javax.swing.JScrollPane();
        Table_Lista = new javax.swing.JTable();

        mnuEditar.setText("Editar");
        mnuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarActionPerformed(evt);
            }
        });
        mnuPopupLista.add(mnuEditar);

        mnuManutencao.setText("jMenuItem1");
        mnuManutencao.setActionCommand("Manutenções");
        mnuPopupLista.add(mnuManutencao);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Panel_Cadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Ficha Tecnica"));

        Label_Marca.setText("Marca");

        Label_Modelo.setText("Modelo");

        Label_Ano.setText("Ano");

        Label_Cor.setText("Cor");

        TextField_Marca.setName(""); // NOI18N

        Spinner_Ano.setModel(new javax.swing.SpinnerNumberModel(2000, 2000, 2030, 1));
        Spinner_Ano.setToolTipText("");
        Spinner_Ano.setValue(2000);

        Label_PMotor.setText("Potência do motor");

        Spinner_PMotor.setModel(new javax.swing.SpinnerNumberModel(1.0d, null, null, 0.10000000000000009d));
        Spinner_PMotor.setToolTipText("");
        Spinner_PMotor.setName(""); // NOI18N
        Spinner_PMotor.setValue(1);

        Label_Combustivel.setText("Combustível");

        ComboBox_Combustivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Álcool", "Diesel", "Elétrico", "Flex", "Gasolina", "Híbrido" }));
        ComboBox_Combustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_CombustivelActionPerformed(evt);
            }
        });

        Label_Cambio.setText("Câmbio");

        Label_Direcao.setText("Direção");

        ComboBox_Cambio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automático", "Manual", "Semi-automático" }));

        ComboBox_Direcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Assistida", "Elétrica", "Hidraulica", "Mecanica" }));

        javax.swing.GroupLayout Panel_CadastroLayout = new javax.swing.GroupLayout(Panel_Cadastro);
        Panel_Cadastro.setLayout(Panel_CadastroLayout);
        Panel_CadastroLayout.setHorizontalGroup(
            Panel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_CadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Modelo)
                    .addComponent(Label_Ano)
                    .addComponent(Label_Cor)
                    .addComponent(Label_Marca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_Cor, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(Spinner_Ano)
                    .addComponent(TextField_Marca)
                    .addComponent(TextField_Modelo))
                .addGap(55, 55, 55)
                .addGroup(Panel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_CadastroLayout.createSequentialGroup()
                        .addComponent(Label_PMotor)
                        .addGap(18, 18, 18)
                        .addComponent(Spinner_PMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_CadastroLayout.createSequentialGroup()
                        .addGroup(Panel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Combustivel)
                            .addComponent(Label_Direcao)
                            .addComponent(Label_Cambio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBox_Cambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_Direcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_Combustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );
        Panel_CadastroLayout.setVerticalGroup(
            Panel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_CadastroLayout.createSequentialGroup()
                .addGroup(Panel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Marca)
                    .addComponent(Label_Combustivel)
                    .addComponent(ComboBox_Combustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Modelo)
                    .addComponent(Label_Cambio)
                    .addComponent(ComboBox_Cambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Ano)
                    .addComponent(Spinner_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Direcao)
                    .addComponent(ComboBox_Direcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(Panel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Cor)
                    .addComponent(Label_PMotor)
                    .addComponent(Spinner_PMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        Label_CADASTRO.setBackground(new java.awt.Color(0, 0, 0));
        Label_CADASTRO.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_CADASTRO.setText("Cadastro de Automóveis");

        Panel_DadosCompra.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da compra"));

        Label_Fornecedor.setText("Fornecedor");

        jLabel9.setText("Valor (R$)");

        Label_Data.setText("Data");

        try {
            FTextField_Data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout Panel_DadosCompraLayout = new javax.swing.GroupLayout(Panel_DadosCompra);
        Panel_DadosCompra.setLayout(Panel_DadosCompraLayout);
        Panel_DadosCompraLayout.setHorizontalGroup(
            Panel_DadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DadosCompraLayout.createSequentialGroup()
                .addGroup(Panel_DadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_DadosCompraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Panel_DadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_DadosCompraLayout.createSequentialGroup()
                                .addComponent(Label_Data)
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_DadosCompraLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_DadosCompraLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Label_Fornecedor)
                        .addGap(18, 18, 18)))
                .addGroup(Panel_DadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FTextField_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        Panel_DadosCompraLayout.setVerticalGroup(
            Panel_DadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DadosCompraLayout.createSequentialGroup()
                .addGroup(Panel_DadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Fornecedor)
                    .addComponent(TextField_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(Panel_DadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(6, 6, 6)
                .addGroup(Panel_DadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Data)
                    .addComponent(FTextField_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        Label_PlacaCarro.setText("Placa do carro");

        TextField_Placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_PlacaActionPerformed(evt);
            }
        });

        Button_Adicionar.setText("Adicionar");
        Button_Adicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AdicionarActionPerformed(evt);
            }
        });

        Button_Editar.setText("Editar");
        Button_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EditarActionPerformed(evt);
            }
        });

        Button_Excluir.setText("Excluir");
        Button_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ExcluirActionPerformed(evt);
            }
        });

        Panel_Lista.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de veiculos não vendidos"));

        Table_Lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Cor", "Ano", "Placa", "Fornecedor", "Valor compra", "Data compra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Lista.setComponentPopupMenu(mnuPopupLista);
        ScrollPane_Lista.setViewportView(Table_Lista);

        javax.swing.GroupLayout Panel_ListaLayout = new javax.swing.GroupLayout(Panel_Lista);
        Panel_Lista.setLayout(Panel_ListaLayout);
        Panel_ListaLayout.setHorizontalGroup(
            Panel_ListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollPane_Lista)
        );
        Panel_ListaLayout.setVerticalGroup(
            Panel_ListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane_Lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel_Lista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Panel_DadosCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Label_PlacaCarro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextField_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(Label_CADASTRO)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button_Adicionar)
                        .addGap(18, 18, 18)
                        .addComponent(Button_Editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_Excluir)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Label_CADASTRO)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel_DadosCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_PlacaCarro)
                            .addComponent(TextField_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Adicionar)
                    .addComponent(Button_Editar)
                    .addComponent(Button_Excluir))
                .addGap(18, 18, 18)
                .addComponent(Panel_Lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_PlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_PlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_PlacaActionPerformed

    
    private void Button_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AdicionarActionPerformed
        String marca = TextField_Marca.getText();
        String modelo = TextField_Modelo.getText();
        int ano = Integer.parseInt(Spinner_Ano.getValue().toString());
        String cor = TextField_Cor.getText();
        String combustivel = ComboBox_Combustivel.getSelectedItem().toString();
        String cambio = ComboBox_Cambio.getSelectedItem().toString();
        String direcao = ComboBox_Direcao.getSelectedItem().toString();
        double p_motor = Double.parseDouble(Spinner_PMotor.getValue().toString());
        
        String fornecedor = TextField_Fornecedor.getText();
        double valor_compra = Double.parseDouble(TextField_Valor.getText());
        String data_compra = FTextField_Data.getText();
        String placa = TextField_Placa.getText();
        
        adicionarTabela(marca,modelo,cor,ano,placa,fornecedor,valor_compra, data_compra);
        //ComboBox_Direcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Assistida", "Elétrica", "Hidraulica", "Mecanica" }));
    }//GEN-LAST:event_Button_AdicionarActionPerformed

    private void adicionarTabela(String marca, String modelo, String cor, int ano, String placa, String fornecedor, double valor_compra, String data_compra){
        ( (DefaultTableModel) Table_Lista.getModel() ).addRow( new Object[8] );
        
        int linha = Table_Lista.getRowCount() - 1;
        int col = 0;
        
        Table_Lista.setValueAt(marca, linha, col++);
        Table_Lista.setValueAt(modelo, linha, col++);
        Table_Lista.setValueAt(cor, linha, col++);
        Table_Lista.setValueAt(ano, linha, col++);
        Table_Lista.setValueAt(placa, linha, col++);
        Table_Lista.setValueAt(fornecedor, linha, col++);
        Table_Lista.setValueAt(valor_compra, linha, col++);
        Table_Lista.setValueAt(data_compra, linha, col++);
        ComboBox_Direcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "teste", "Elétrica", "Hidraulica", "Mecanica" }));
        limparCampos();
        
    }
    
    private void limparCampos(){
        TextField_Marca.setText("");
        TextField_Modelo.setText("");
        Spinner_Ano.setValue(2000);
        TextField_Cor.setText("");
        ComboBox_Combustivel.setSelectedIndex(0);
        ComboBox_Cambio.setSelectedIndex(0);
        ComboBox_Direcao.setSelectedIndex(0);
        Spinner_PMotor.setValue(1);
        TextField_Fornecedor.setText("");
        TextField_Valor.setText("");
        FTextField_Data.setText("");
        TextField_Placa.setText("");

       /* String modelo = .getText();
        int ano = Integer.parseInt(.getValue().toString());
        String cor = .getText();
        String combustivel = .getSelectedItem().toString();
        String cambio = .getSelectedItem().toString();
        String direcao = .getSelectedItem().toString();
        double p_motor = Double.parseDouble(.getValue().toString());
        
        String fornecedor = .getText();
        double valor_compra = Double.parseDouble(.getText());
        String data_compra = .getText();
        String placa = .getText();
        */
    }

    private void ComboBox_CombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_CombustivelActionPerformed

    }//GEN-LAST:event_ComboBox_CombustivelActionPerformed

    private void Button_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ExcluirActionPerformed
        int linhaSelecionada = Table_Lista.getSelectedRow();
        if(linhaSelecionada >= 0){
            if(JOptionPane.showConfirmDialog(this, "Desejar realmente excluir?", "Título", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
              ( (DefaultTableModel) Table_Lista.getModel() ).removeRow(linhaSelecionada);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Selecione uma linha.", "Título", JOptionPane.ERROR_MESSAGE);
        }
          
    }//GEN-LAST:event_Button_ExcluirActionPerformed

    private void Button_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EditarActionPerformed
        int linhaSelecionada = Table_Lista.getSelectedRow();
        int col = 0;
        TextField_Marca.setText(Table_Lista.getValueAt(linhaSelecionada, col++).toString());
        TextField_Modelo.setText(Table_Lista.getValueAt(linhaSelecionada, col++).toString());
        Spinner_Ano.setValue(Table_Lista.getValueAt(linhaSelecionada, col++));
       // TextField_Cor.setText(Table_Lista.getValueAt(linhaSelecionada, col++).toString());
        TextField_Placa.setText(Table_Lista.getValueAt(linhaSelecionada, col++).toString());
        TextField_Fornecedor.setText(Table_Lista.getValueAt(linhaSelecionada, col++).toString());
        TextField_Valor.setText(Table_Lista.getValueAt(linhaSelecionada, col++).toString());
        FTextField_Data.setText(Table_Lista.getValueAt(linhaSelecionada, col++).toString());    
        
        
        
        
    }//GEN-LAST:event_Button_EditarActionPerformed

    private void mnuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarActionPerformed
        
    }//GEN-LAST:event_mnuEditarActionPerformed
      

    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cadastro dialog = new Cadastro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Adicionar;
    private javax.swing.JButton Button_Editar;
    private javax.swing.JButton Button_Excluir;
    private javax.swing.JComboBox<String> ComboBox_Cambio;
    private javax.swing.JComboBox<String> ComboBox_Combustivel;
    private javax.swing.JComboBox<String> ComboBox_Direcao;
    private javax.swing.JFormattedTextField FTextField_Data;
    private javax.swing.JLabel Label_Ano;
    private javax.swing.JLabel Label_CADASTRO;
    private javax.swing.JLabel Label_Cambio;
    private javax.swing.JLabel Label_Combustivel;
    private javax.swing.JLabel Label_Cor;
    private javax.swing.JLabel Label_Data;
    private javax.swing.JLabel Label_Direcao;
    private javax.swing.JLabel Label_Fornecedor;
    private javax.swing.JLabel Label_Marca;
    private javax.swing.JLabel Label_Modelo;
    private javax.swing.JLabel Label_PMotor;
    private javax.swing.JLabel Label_PlacaCarro;
    private javax.swing.JPanel Panel_Cadastro;
    private javax.swing.JPanel Panel_DadosCompra;
    private javax.swing.JPanel Panel_Lista;
    private javax.swing.JScrollPane ScrollPane_Lista;
    private javax.swing.JSpinner Spinner_Ano;
    private javax.swing.JSpinner Spinner_PMotor;
    private javax.swing.JTable Table_Lista;
    private javax.swing.JTextField TextField_Cor;
    private javax.swing.JTextField TextField_Fornecedor;
    private javax.swing.JTextField TextField_Marca;
    private javax.swing.JTextField TextField_Modelo;
    private javax.swing.JTextField TextField_Placa;
    private javax.swing.JTextField TextField_Valor;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JMenuItem mnuEditar;
    private javax.swing.JMenuItem mnuManutencao;
    private javax.swing.JPopupMenu mnuPopupLista;
    // End of variables declaration//GEN-END:variables
}
