/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import javax.swing.JPanel;

/**
 *
 * @author William
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form SistemaRevenda
     */
    public JanelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        pnlDashboard = new RoundedPanel(5, new Color(255, 255, 255));
        lblDashboard = new javax.swing.JLabel();
        lblProfile = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlLucroMedio = new javax.swing.JPanel();
        lblVendas2 = new javax.swing.JLabel();
        lblVendasValor = new javax.swing.JLabel();
        pnlLucroTotal = new javax.swing.JPanel();
        lblVendas1 = new javax.swing.JLabel();
        lblVendasValor2 = new javax.swing.JLabel();
        pnlVendas = new javax.swing.JPanel();
        lblVendas = new javax.swing.JLabel();
        lblVendasValor1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlDashboard2 = new javax.swing.JPanel();
        lblDashboard2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 0, 0));
        setFocusable(false);
        setFocusableWindowState(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(67, 46, 128));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDashboard.setBackground(new java.awt.Color(255, 255, 255));

        lblDashboard.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(0, 0, 0));
        lblDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDashboard.setText("Dashboard");

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDashboardLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlMenu.add(pnlDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, -1));

        lblProfile.setIcon(new javax.swing.ImageIcon("C:\\Users\\William\\Documents\\NetBeansProjects\\javaswing\\SistemaRevendaCamadas\\src\\main\\java\\imagens\\profile (2).png")); // NOI18N
        pnlMenu.add(lblProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        lblUser.setBackground(new java.awt.Color(255, 255, 255));
        lblUser.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("William");
        pnlMenu.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 690));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlLucroMedio.setBackground(new java.awt.Color(138, 80, 255));

        lblVendas2.setFont(new java.awt.Font("TangoSans", 0, 24)); // NOI18N
        lblVendas2.setForeground(new java.awt.Color(255, 255, 255));
        lblVendas2.setText("LUCRO MÉDIO");

        lblVendasValor.setBackground(new java.awt.Color(255, 255, 255));
        lblVendasValor.setFont(new java.awt.Font("TangoSans", 0, 24)); // NOI18N
        lblVendasValor.setForeground(new java.awt.Color(255, 255, 255));
        lblVendasValor.setText("R$ 1500,54");

        javax.swing.GroupLayout pnlLucroMedioLayout = new javax.swing.GroupLayout(pnlLucroMedio);
        pnlLucroMedio.setLayout(pnlLucroMedioLayout);
        pnlLucroMedioLayout.setHorizontalGroup(
            pnlLucroMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLucroMedioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLucroMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVendas2)
                    .addComponent(lblVendasValor))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnlLucroMedioLayout.setVerticalGroup(
            pnlLucroMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLucroMedioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblVendas2)
                .addGap(18, 18, 18)
                .addComponent(lblVendasValor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlLucroTotal.setBackground(new java.awt.Color(122, 232, 74));

        lblVendas1.setFont(new java.awt.Font("TangoSans", 0, 24)); // NOI18N
        lblVendas1.setForeground(new java.awt.Color(255, 255, 255));
        lblVendas1.setText("LUCRO TOTAL");

        lblVendasValor2.setBackground(new java.awt.Color(255, 255, 255));
        lblVendasValor2.setFont(new java.awt.Font("TangoSans", 0, 24)); // NOI18N
        lblVendasValor2.setForeground(new java.awt.Color(255, 255, 255));
        lblVendasValor2.setText("R$ 101.150,10");

        javax.swing.GroupLayout pnlLucroTotalLayout = new javax.swing.GroupLayout(pnlLucroTotal);
        pnlLucroTotal.setLayout(pnlLucroTotalLayout);
        pnlLucroTotalLayout.setHorizontalGroup(
            pnlLucroTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLucroTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLucroTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVendas1)
                    .addComponent(lblVendasValor2))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlLucroTotalLayout.setVerticalGroup(
            pnlLucroTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLucroTotalLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblVendas1)
                .addGap(18, 18, 18)
                .addComponent(lblVendasValor2)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnlVendas.setBackground(new java.awt.Color(56, 182, 255));

        lblVendas.setFont(new java.awt.Font("TangoSans", 0, 24)); // NOI18N
        lblVendas.setForeground(new java.awt.Color(255, 255, 255));
        lblVendas.setText("VENDAS");

        lblVendasValor1.setBackground(new java.awt.Color(255, 255, 255));
        lblVendasValor1.setFont(new java.awt.Font("TangoSans", 0, 24)); // NOI18N
        lblVendasValor1.setForeground(new java.awt.Color(255, 255, 255));
        lblVendasValor1.setText("0");

        javax.swing.GroupLayout pnlVendasLayout = new javax.swing.GroupLayout(pnlVendas);
        pnlVendas.setLayout(pnlVendasLayout);
        pnlVendasLayout.setHorizontalGroup(
            pnlVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVendasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVendasValor1)
                    .addComponent(lblVendas))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        pnlVendasLayout.setVerticalGroup(
            pnlVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVendasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblVendas)
                .addGap(18, 18, 18)
                .addComponent(lblVendasValor1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(45, 45, 45)
                        .addComponent(pnlLucroMedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(45, 45, 45)
                        .addComponent(pnlLucroTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlLucroTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLucroMedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 690, 620));

        pnlDashboard2.setBackground(new java.awt.Color(255, 222, 89));

        lblDashboard2.setFont(new java.awt.Font("TangoSans", 0, 36)); // NOI18N
        lblDashboard2.setForeground(new java.awt.Color(0, 0, 0));
        lblDashboard2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDashboard2.setText("DASHBOARD");

        javax.swing.GroupLayout pnlDashboard2Layout = new javax.swing.GroupLayout(pnlDashboard2);
        pnlDashboard2.setLayout(pnlDashboard2Layout);
        pnlDashboard2Layout.setHorizontalGroup(
            pnlDashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDashboard2, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        pnlDashboard2Layout.setVerticalGroup(
            pnlDashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDashboard2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(pnlDashboard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 690, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblDashboard2;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblVendas;
    private javax.swing.JLabel lblVendas1;
    private javax.swing.JLabel lblVendas2;
    private javax.swing.JLabel lblVendasValor;
    private javax.swing.JLabel lblVendasValor1;
    private javax.swing.JLabel lblVendasValor2;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlDashboard2;
    private javax.swing.JPanel pnlLucroMedio;
    private javax.swing.JPanel pnlLucroTotal;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlVendas;
    // End of variables declaration//GEN-END:variables


    class RoundedPanel extends JPanel{
        private Color backgroundColor;
        private int cornerRadius = 15;
        
        public RoundedPanel(LayoutManager layout, int radius){
            super(layout);
            cornerRadius = radius;
        }
        
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor){
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        
        public RoundedPanel(int radius){
            super();
            cornerRadius = radius;
        }
        
        public RoundedPanel(int radius, Color bgColor){
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        
        @Override
        protected void paintComponent(Graphics g){
            super.paintComponents(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            
            if(backgroundColor != null){
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height);
            graphics.setColor(getForeground());
        } 
    }    
}
